name: CI - Dump model info

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Dump model info
    runs-on: macos-13
    if: github.repository_owner == 'dortania'


    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Dump model info
        run: python3 OpenCore-Patcher-GUI.command --help